### ISSUE TITLE
Incorrect "Recommendation to conservationists"

### ISSUE THREAD

**Issue by JagaRamesh** [Choppy1884/intro-data-capstone-biodiversity#1]
The mentioned recommendation for conservationists is to pay more attention to Vascular plants based on the number of protected species.
It's best to look at the "percent protected" instead of the numbers on "protected". 
For example, in Vascular plants, out of the total 4262 species, 4216 are not protected and only 46 is protected. So, only 1% of species is protected.
In Mammals and birds, about 17% and 15% are protected which indicates that Mammals and Birds are more endangered.

**Comment by Choppy1884** [comment]
Hi, Yes i re-read the data and realised i had read it the wrong way, i've ran through it again, updated my project and provided another recommendation, Thanks again for the feedback!
