### ISSUE TITLE
For sample size 870, Incorrect no of weeks

### ISSUE THREAD

**Issue by JagaRamesh** [Choppy1884/intro-data-capstone-biodiversity#2]
I noticed you have highlighted the sample size as 870 and mentioned 
(i) no of weeks needed for Bryce is approximately 2 weeks and 
(ii)for yellow stone , it is around one week.

For sample size 870, the "no of weeks" calculation would be :
No of weeks needed for Yellow stone = 870 / 507.0 = 1.7 (close to 2 weeks)
No of weeks needed for Bryce = 870 / 250.0 = 3.48 (close to 3 and 1/2 weeks)

**Comment by Choppy1884** [comment]
Thanks again for the feedback, i reviewed the data again and you are correct, 
i've corrected this and resubmitted my project
