### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [Choppy1884/intro-data-capstone-biodiversity#3]
Great job explaining the analysis and the outcome in the document.

I noticed that the objective of analysis was missing for both "Endangered species" and "Foot and mouth disease". It's a best practice to start the document with the objective/purpose and conclude with your findings.

The matplotlib plots are neat with proper title, xlabel and ylabel defined. I would suggest to use the plots as a part of the analysis rather than showing them in the last two slides.

The chi-square results and its interpretation of Endangered species is correct. But the final recommendation to conservationists is incorrect. I have created a separate issue for the same.

For Foot & Mouth disease, the Baseline, Minimum Detectable Effect, the Sample size calculation is accurate. But the no of weeks needed for observation of sheep is incorrect. Please check the issue for details.

Overall Good work!

**Comment by Choppy1884** [comment]
Thanks for the feedback, very helpful and appreciate it!
